/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PhotographersRouteImport } from './routes/photographers'
import { Route as AuthAboutMeRouteImport } from './routes/_auth.about-me'
import { Route as AuthManagementRouteImport } from './routes/_auth.management'
import { Route as AuthorAuthorIdOrNameRouteImport } from './routes/author.$authorIdOrName'
import { Route as GalleryGalleryIdRouteImport } from './routes/gallery.$galleryId'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth.admin.index'
import { Route as AuthAdminGalleryGalleryIdRouteImport } from './routes/_auth.admin.gallery.$galleryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersRoute = PhotographersRouteImport.update({
  id: '/photographers',
  path: '/photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAboutMeRoute = AuthAboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagementRoute = AuthManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AuthRoute,
} as any)
const AuthorAuthorIdOrNameRoute = AuthorAuthorIdOrNameRouteImport.update({
  id: '/author/$authorIdOrName',
  path: '/author/$authorIdOrName',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryGalleryIdRoute = GalleryGalleryIdRouteImport.update({
  id: '/gallery/$galleryId',
  path: '/gallery/$galleryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminGalleryGalleryIdRoute =
  AuthAdminGalleryGalleryIdRouteImport.update({
    id: '/admin/gallery/$galleryId',
    path: '/admin/gallery/$galleryId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/photographers': typeof PhotographersRoute
  '/about-me': typeof AuthAboutMeRoute
  '/management': typeof AuthManagementRoute
  '/author/$authorIdOrName': typeof AuthorAuthorIdOrNameRoute
  '/gallery/$galleryId': typeof GalleryGalleryIdRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/admin/gallery/$galleryId': typeof AuthAdminGalleryGalleryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/photographers': typeof PhotographersRoute
  '/about-me': typeof AuthAboutMeRoute
  '/management': typeof AuthManagementRoute
  '/author/$authorIdOrName': typeof AuthorAuthorIdOrNameRoute
  '/gallery/$galleryId': typeof GalleryGalleryIdRoute
  '/admin': typeof AuthAdminIndexRoute
  '/admin/gallery/$galleryId': typeof AuthAdminGalleryGalleryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/photographers': typeof PhotographersRoute
  '/_auth/about-me': typeof AuthAboutMeRoute
  '/_auth/management': typeof AuthManagementRoute
  '/author/$authorIdOrName': typeof AuthorAuthorIdOrNameRoute
  '/gallery/$galleryId': typeof GalleryGalleryIdRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/admin/gallery/$galleryId': typeof AuthAdminGalleryGalleryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/logout'
    | '/photographers'
    | '/about-me'
    | '/management'
    | '/author/$authorIdOrName'
    | '/gallery/$galleryId'
    | '/admin/'
    | '/admin/gallery/$galleryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/logout'
    | '/photographers'
    | '/about-me'
    | '/management'
    | '/author/$authorIdOrName'
    | '/gallery/$galleryId'
    | '/admin'
    | '/admin/gallery/$galleryId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/logout'
    | '/photographers'
    | '/_auth/about-me'
    | '/_auth/management'
    | '/author/$authorIdOrName'
    | '/gallery/$galleryId'
    | '/_auth/admin/'
    | '/_auth/admin/gallery/$galleryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PhotographersRoute: typeof PhotographersRoute
  AuthorAuthorIdOrNameRoute: typeof AuthorAuthorIdOrNameRoute
  GalleryGalleryIdRoute: typeof GalleryGalleryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers': {
      id: '/photographers'
      path: '/photographers'
      fullPath: '/photographers'
      preLoaderRoute: typeof PhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/about-me': {
      id: '/_auth/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AuthAboutMeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/management': {
      id: '/_auth/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthManagementRouteImport
      parentRoute: typeof AuthRoute
    }
    '/author/$authorIdOrName': {
      id: '/author/$authorIdOrName'
      path: '/author/$authorIdOrName'
      fullPath: '/author/$authorIdOrName'
      preLoaderRoute: typeof AuthorAuthorIdOrNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$galleryId': {
      id: '/gallery/$galleryId'
      path: '/gallery/$galleryId'
      fullPath: '/gallery/$galleryId'
      preLoaderRoute: typeof GalleryGalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/gallery/$galleryId': {
      id: '/_auth/admin/gallery/$galleryId'
      path: '/admin/gallery/$galleryId'
      fullPath: '/admin/gallery/$galleryId'
      preLoaderRoute: typeof AuthAdminGalleryGalleryIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAboutMeRoute: typeof AuthAboutMeRoute
  AuthManagementRoute: typeof AuthManagementRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAdminGalleryGalleryIdRoute: typeof AuthAdminGalleryGalleryIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAboutMeRoute: AuthAboutMeRoute,
  AuthManagementRoute: AuthManagementRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAdminGalleryGalleryIdRoute: AuthAdminGalleryGalleryIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PhotographersRoute: PhotographersRoute,
  AuthorAuthorIdOrNameRoute: AuthorAuthorIdOrNameRoute,
  GalleryGalleryIdRoute: GalleryGalleryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
